name = "GCATBase"
uuid = "5da00781-4ec7-4633-a007-8ceb506d1ca1"
authors = ["Markus Gumbel <m.gumbel@hs-mannheim.de>"]
version = "0.2.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioSymbols = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"

[compat]
BioSequences = "3.5.0"
BioSymbols = "5.2.0"
DocStringExtensions = "0.9.5"
Pipe = "1.3.0"

